on: [push, pull_request]

name: Continuous integration

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - name: Run Clippy
        run: cargo clippy
